
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AnalyticsDashboard = lazy(() => import("./pages/AnalyticsDashboard.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const DocumentDetailsPage = lazy(() => import("./pages/DocumentDetailsPage.tsx"));
const DocumentManager = lazy(() => import("./pages/DocumentManager.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const PasswordResetPage = lazy(() => import("./pages/PasswordResetPage.tsx"));
const ProcessingManagement = lazy(() => import("./pages/ProcessingManagement.tsx"));
const ProjectsPage = lazy(() => import("./pages/ProjectsPage.tsx"));
const SignupPage = lazy(() => import("./pages/SignupPage.tsx"));
const UploadPage = lazy(() => import("./pages/UploadPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/analytics-dashboard", element: <AnalyticsDashboard />},
	{ path: "/analyticsdashboard", element: <AnalyticsDashboard />},
	{ path: "/", element: <App />},
	{ path: "/document-details-page", element: <DocumentDetailsPage />},
	{ path: "/documentdetailspage", element: <DocumentDetailsPage />},
	{ path: "/document-manager", element: <DocumentManager />},
	{ path: "/documentmanager", element: <DocumentManager />},
	{ path: "/login-page", element: <LoginPage />},
	{ path: "/loginpage", element: <LoginPage />},
	{ path: "/password-reset-page", element: <PasswordResetPage />},
	{ path: "/passwordresetpage", element: <PasswordResetPage />},
	{ path: "/processing-management", element: <ProcessingManagement />},
	{ path: "/processingmanagement", element: <ProcessingManagement />},
	{ path: "/projects-page", element: <ProjectsPage />},
	{ path: "/projectspage", element: <ProjectsPage />},
	{ path: "/signup-page", element: <SignupPage />},
	{ path: "/signuppage", element: <SignupPage />},
	{ path: "/upload-page", element: <UploadPage />},
	{ path: "/uploadpage", element: <UploadPage />},

];
